version: "3.7"

volumes:
    pgsql:
        name: kali-msf-pgsql

services:
    kali:
        image: aymdev/kali-linux:latest
        network_mode: "host"
        volumes:
            - pgsql:/var/lib/postgresql
            - ./root:/root
            - /var/run/dbus:/var/run/dbus
        privileged: true
        entrypoint: /bin/bash