version: "3.7"

volumes:
    pgsql:
        name: kali-msf-pgsql

services:
    kali:
        build: ./build
        network_mode: "host"
        volumes:
            - pgsql:/var/lib/postgresql
            - ./root:/root
        entrypoint: /bin/bash